# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - VMusicSite

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d1b5040df9bc46a9a9a34a307d550386 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_15f3a344b0834fd4ac3677ffb1ea4545 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d1b5040df9bc46a9a9a34a307d550386 }}/phanan/koel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'VMusicSite'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1e2ca9c0ccd94eb6a772190b8fad514f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d1b5040df9bc46a9a9a34a307d550386 }}/phanan/koel:${{ github.sha }}'